version: "1.0"
services:   
  frontend:
    image: "httpd:2.4"
    container_name: apache-bind-demo 
    ports:
            - "8080:80"
    volumes:
      - type: bind
        source: demoPage
        target: /usr/local/apache2/htdocs/
